name: owl_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_line: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
   - lib/images/owl.png
   - lib/images/owlfly.png
   - lib/images/iconlixo.png
   - lib/images/iconadd.png
   - lib/images/iconchecked.png
   - lib/images/iconexcluir.png
